networks:
  default:
    name: z51_network
    external: true

services:
  z51_21_p_server:
    container_name: z51_21_p_server
    build: ./p_server

  z51_21_p_server_c_client:
    container_name: z51_21_p_server_c_client
    build: ./c_client
    tty: true
    depends_on:
      - z51_21_p_server
    command: ["./c_client", "z51_21_p_server", "8000", "5"]
